AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  npmregistryagent:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 15
      Role: >-
        arn:aws:iam::985522916759:role/service-role/npm-registry-agent-role-hmr1xvi6
      Events:
        root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        catch-all:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
      Environment:
        Variables:
          GITHUB_HOST: 'expose host name'
          GITHUB_TOKEN: '`read:package` personal access token'
